"""Add file_path column to History model

Revision ID: 2be32d6b56f3
Revises: 7fda77dfcebb
Create Date: 2025-02-17 03:39:52.251160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2be32d6b56f3'
down_revision = '7fda77dfcebb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=500), nullable=True))
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
